/* Generated classic-script runtime for Sapphire WebEngine.
 * Source of truth: app.js and the helper modules next to it.
 * Do not edit this file by hand; package-widget.ps1 regenerates it.
 */
(function markNeteaseLyricsRuntime() {
  document.documentElement.dataset.neteaseLyricsRuntime = '0.1.9';
  window.__neteaseLyricsRuntime = { version: '0.1.9', started: true, bridgeConnected: false };
})();

/* --- settings.js --- */
const SETTINGS_KEY = 'neteaseLyricsGlass.settings.v1';

const DEFAULT_SETTINGS = Object.freeze({
  fontSize: 26,
  maxChars: 56,
  color: '#F7FBFF'
});

function clampInteger(value, min, max, fallback) {
  const parsed = Number.parseInt(value, 10);
  return Number.isFinite(parsed) ? Math.min(max, Math.max(min, parsed)) : fallback;
}

function getDefaultStorage() {
  try {
    return globalThis.localStorage;
  } catch {
    return null;
  }
}

function normalizeColor(value) {
  return typeof value === 'string' && /^#[0-9a-f]{6}$/i.test(value)
    ? value.toUpperCase()
    : DEFAULT_SETTINGS.color;
}

function normalizeSettings(input = {}) {
  return {
    fontSize: clampInteger(input.fontSize, 16, 48, DEFAULT_SETTINGS.fontSize),
    maxChars: clampInteger(input.maxChars, 20, 180, DEFAULT_SETTINGS.maxChars),
    color: normalizeColor(input.color)
  };
}

function loadSettings(storage = getDefaultStorage()) {
  try {
    if (!storage || typeof storage.getItem !== 'function') return { ...DEFAULT_SETTINGS };
    return normalizeSettings(JSON.parse(storage.getItem(SETTINGS_KEY) ?? '{}'));
  } catch {
    return { ...DEFAULT_SETTINGS };
  }
}

function saveSettings(next, storage = getDefaultStorage()) {
  const normalized = normalizeSettings(next);
  try {
    if (storage && typeof storage.setItem === 'function') {
      storage.setItem(SETTINGS_KEY, JSON.stringify(normalized));
    }
  } catch {
    // Sapphire may expose an opaque WebEngine origin without writable storage.
  }
  return normalized;
}

/* --- lyric-view-model.js --- */
function asCodePoints(text) {
  return Array.from(String(text ?? ''));
}

function truncateText(text, maxChars) {
  if (text == null || text === '') return null;
  const points = asCodePoints(text);
  const limit = Math.max(1, Number.parseInt(maxChars, 10) || 1);
  return points.length <= limit ? points.join('') : `${points.slice(0, Math.max(0, limit - 1)).join('')}…`;
}

function validLine(line) {
  return line && Number.isFinite(Number(line.startMs)) && String(line.original ?? '').trim() !== '';
}

function selectDisplayLines(lines = [], positionMs = 0, maxChars = 56) {
  const usableLines = lines
    .filter(validLine)
    .map((line) => ({ ...line, startMs: Number(line.startMs) }))
    .sort((left, right) => left.startMs - right.startMs);
  const currentIndex = usableLines.reduce(
    (index, line, candidateIndex) => (line.startMs <= positionMs ? candidateIndex : index),
    -1
  );
  const current = currentIndex >= 0 ? usableLines[currentIndex] : null;
  const next = currentIndex < 0 ? (usableLines[0] ?? null) : (usableLines[currentIndex + 1] ?? null);

  return {
    currentOriginal: truncateText(current?.original, maxChars),
    currentTranslation: truncateText(current?.translation, maxChars),
    nextOriginal: truncateText(next?.original, maxChars)
  };
}

/* --- preview-mode.js --- */
const SUPPORTED_PREVIEW_MODES = new Set(['wide', 'stacked', 'compact']);
const VISUAL_PREVIEW_PARENT = '/visual-style.html';

function getVisualPreviewMode(search, referrer, isEmbedded) {
  if (!isEmbedded) return null;
  const mode = new URLSearchParams(search).get('__sapphireVisualPreview');
  if (!SUPPORTED_PREVIEW_MODES.has(mode)) return null;

  try {
    return new URL(referrer).pathname.endsWith(VISUAL_PREVIEW_PARENT) ? mode : null;
  } catch {
    return null;
  }
}
function createVisualPreviewSnapshot(mode) {
  if (!SUPPORTED_PREVIEW_MODES.has(mode)) return null;

  return {
    trackSessionId: `visual-preview-${mode}`,
    bridge: { status: 'ready' },
    track: { title: 'Liquid Glass · 视觉预览', artist: 'Sapphire' },
    playback: { state: 'paused', positionMs: 12000 },
    lyrics: {
      status: 'ready',
      lines: [
        { startMs: 0, original: 'Every story has an echo', translation: '每个故事都有回响' },
        { startMs: 12000, original: 'Moonlight on the sea', translation: '月光洒落海面' },
        { startMs: 18000, original: 'The night grows bright', translation: '长夜渐亮' }
      ]
    }
  };
}

/* --- responsive-layout.js --- */
function selectResponsiveLayout(width, height) {
  const resolvedWidth = Number.isFinite(width) ? width : 0;
  const resolvedHeight = Number.isFinite(height) ? height : 0;

  if (resolvedHeight < 105) return 'compact';
  return resolvedWidth >= 560 ? 'wide' : 'stacked';
}

/* --- playback-state.js --- */
const PLAYING_STATE_NAMES = new Set(['playing', 'play']);

function normalizedPositionMs(value) {
  const numeric = Number(value);
  return Number.isFinite(numeric) ? Math.max(0, numeric) : 0;
}

function isPlayingState(value) {
  if (typeof value === 'number') return Number.isFinite(value) && value === 0;

  const normalized = String(value ?? '').trim().toLowerCase();
  return PLAYING_STATE_NAMES.has(normalized) || normalized === '0';
}

function effectivePlaybackPositionMs(playback, anchor, nowMs = performance.now()) {
  const positionMs = normalizedPositionMs(playback?.positionMs);
  if (!isPlayingState(playback?.state) || !anchor) return positionMs;

  const elapsedMs = Math.max(0, Number(nowMs) - Number(anchor.monotonicMs));
  return Math.max(0, positionMs + elapsedMs);
}

/**
 * Maintains a local monotonic playback clock between sparse or stale SMTC snapshots.
 * A playing snapshot with the same reported position must not reset the clock.
 */
function createPlaybackClock({ resyncThresholdMs = 1500 } = {}) {
  const threshold = Math.max(0, Number(resyncThresholdMs) || 0);
  let state = {
    sessionId: null,
    playbackState: null,
    basePositionMs: 0,
    anchorMonotonicMs: null,
    lastReportedPositionMs: null
  };

  function update(sessionId, playback, nowMs = performance.now()) {
    const positionMs = normalizedPositionMs(playback?.positionMs);
    const playing = isPlayingState(playback?.state);
    const sessionChanged = state.sessionId !== sessionId;

    if (sessionChanged || !playing || !isPlayingState(state.playbackState)) {
      state = {
        sessionId,
        playbackState: playback?.state ?? null,
        basePositionMs: positionMs,
        anchorMonotonicMs: playing ? nowMs : null,
        lastReportedPositionMs: positionMs
      };
      return;
    }

    const estimatedPositionMs = state.anchorMonotonicMs === null
      ? state.basePositionMs
      : state.basePositionMs + Math.max(0, nowMs - state.anchorMonotonicMs);
    const repeatedPosition = state.lastReportedPositionMs === positionMs;

    // Keep the monotonic estimate for repeated stale reports. Resync only when
    // a new report clearly indicates a seek or a large timeline discontinuity.
    if (!repeatedPosition && Math.abs(positionMs - estimatedPositionMs) > threshold) {
      state.basePositionMs = positionMs;
      state.anchorMonotonicMs = nowMs;
    }

    state.playbackState = playback?.state ?? null;
    state.lastReportedPositionMs = positionMs;
  }

  function position(playback, nowMs = performance.now()) {
    const positionMs = normalizedPositionMs(playback?.positionMs);
    if (!isPlayingState(playback?.state) || state.anchorMonotonicMs === null) return positionMs;

    return Math.max(0, state.basePositionMs + Math.max(0, nowMs - state.anchorMonotonicMs));
  }

  function reset() {
    state = {
      sessionId: null,
      playbackState: null,
      basePositionMs: 0,
      anchorMonotonicMs: null,
      lastReportedPositionMs: null
    };
  }

  return { update, position, reset };
}

/* --- sapphire-smtc.js --- */
function parseJsonObject(value) {
  if (value && typeof value === 'object' && !Array.isArray(value)) return value;
  if (typeof value !== 'string' || value.trim() === '') return null;
  try {
    const parsed = JSON.parse(value);
    return parsed && typeof parsed === 'object' && !Array.isArray(parsed) ? parsed : null;
  } catch {
    return null;
  }
}

function trimmedString(value) {
  return typeof value === 'string' && value.trim() !== '' ? value.trim() : null;
}

function nonNegativeMs(value) {
  const numeric = Number(value);
  return Number.isFinite(numeric) ? Math.max(0, Math.round(numeric)) : 0;
}

function toPlaybackState(value) {
  // Sapphire's QML-facing SMTC status is localized (for example, "播放中")
  // while some builds expose the English or numeric enum value. Normalize all
  // known representations before sending the update to the bridge.
  if (typeof value === 'number' && Number.isFinite(value)) {
    if (value === 0) return 'Playing';
    if (value === 1) return 'Paused';
    return 'Stopped';
  }

  const normalized = String(value ?? '').trim().toLowerCase();
  if (['playing', 'play', '播放中', '正在播放', '播放'].includes(normalized)) {
    return 'Playing';
  }
  if (['paused', 'pause', '已暂停', '暂停播放', '暂停'].includes(normalized)) {
    return 'Paused';
  }
  return 'Stopped';
}

function artistsFrom(value) {
  const artist = trimmedString(value);
  if (!artist) return [];

  return artist
    .split(/\s*(?:\/|、|;|；)\s*/u)
    .map((name) => name.trim())
    .filter(Boolean);
}

function isNeteaseApplicationName(value) {
  const applicationName = trimmedString(value);
  return applicationName !== null && /netease|cloudmusic|网易云/ui.test(applicationName);
}

function createUpdateFromValues(media, playback, now = new Date()) {
  if (!media || media.enabled === false || playback.enabled === false) return null;

  const sourceAppUserModelId = trimmedString(media.appName);
  const title = trimmedString(media.mediaTitle);
  if (!sourceAppUserModelId || !title || !isNeteaseApplicationName(sourceAppUserModelId)) return null;

  const timestamp = now instanceof Date ? now : new Date(now);
  if (Number.isNaN(timestamp.getTime())) return null;

  return {
    sourceAppUserModelId,
    title,
    artists: artistsFrom(media.mediaArtist),
    album: trimmedString(media.mediaAlbum),
    durationMs: nonNegativeMs(playback.playbackDuration),
    state: toPlaybackState(playback.playbackStatus),
    positionMs: nonNegativeMs(playback.playbackPosition),
    updatedAt: timestamp.toISOString()
  };
}

function createSapphireSmtcUpdate(mediaJson, playbackJson, now = new Date()) {
  const media = parseJsonObject(mediaJson);
  // Sapphire may publish the media property before the playback property finishes
  // initializing. Media metadata is sufficient to start a lyrics lookup; a later
  // playback signal will refine timeline and state.
  const playback = parseJsonObject(playbackJson) ?? { enabled: true };
  return createUpdateFromValues(media, playback, now);
}

function createSapphireSmtcUpdateFromBridge(bridge, now = new Date()) {
  if (!bridge || typeof bridge !== 'object') return null;

  // Older Sapphire builds exposed two JSON strings. Current SWidget.qml exposes
  // the same data as separate Q_PROPERTY values, so use the JSON values as a
  // base and fill any missing fields from the direct properties.
  const mediaJson = parseJsonObject(bridge.smtcMediaInfo) ?? {};
  const playbackJson = parseJsonObject(bridge.smtcPlaybackStatus) ?? {};
  const media = {
    ...mediaJson,
    appName: trimmedString(mediaJson.appName) ?? trimmedString(bridge.smtcAppName),
    mediaTitle: trimmedString(mediaJson.mediaTitle) ?? trimmedString(bridge.smtcMediaTitle),
    mediaArtist: trimmedString(mediaJson.mediaArtist) ?? trimmedString(bridge.smtcMediaArtist),
    mediaAlbum: trimmedString(mediaJson.mediaAlbum) ?? trimmedString(bridge.smtcMediaAlbum)
  };
  const playback = {
    ...playbackJson,
    playbackStatus: playbackJson.playbackStatus ?? bridge.smtcPlaybackStatus,
    playbackPosition: playbackJson.playbackPosition ?? bridge.smtcPlaybackPosition,
    playbackDuration: playbackJson.playbackDuration ?? bridge.smtcPlaybackDuration
  };

  return createUpdateFromValues(media, playback, now);
}

function connectSignal(signal, handler) {
  if (signal && typeof signal.connect === 'function') {
    signal.connect(handler);
    return true;
  }

  return false;
}

function startSapphireSmtc(onUpdate, runtime = globalThis) {
  if (typeof onUpdate !== 'function') throw new TypeError('onUpdate must be a function');

  const qt = runtime?.qt;
  const QWebChannel = runtime?.QWebChannel;
  if (!qt?.webChannelTransport || typeof QWebChannel !== 'function') {
    return { connected: false, dispose() {} };
  }

  let disposed = false;
  let pollHandle = null;
  const emit = () => {
    if (disposed) return;
    const bridge = currentBridge;
    const update = createSapphireSmtcUpdateFromBridge(bridge);
    if (update) void Promise.resolve(onUpdate(update)).catch(() => {});
  };
  let currentBridge = null;

  new QWebChannel(qt.webChannelTransport, (channel) => {
    if (disposed) return;
    currentBridge = channel?.objects?.bridge ?? null;
    if (!currentBridge) return;

    [
      'smtcMediaInfoChanged',
      'smtcMediaTitleChanged',
      'smtcMediaArtistChanged',
      'smtcMediaAlbumChanged',
      'smtcAppNameChanged',
      'smtcPlaybackStatusChanged',
      'smtcPlaybackPositionChanged',
      'smtcPlaybackDurationChanged'
    ].forEach((signalName) => connectSignal(currentBridge[signalName], emit));

    // Sapphire's official WebChannel sample defers its first reactive property
    // read, because the C++ side can finish filling these properties just after
    // the QWebChannel callback runs.
    const schedule = typeof runtime?.setTimeout === 'function'
      ? runtime.setTimeout.bind(runtime)
      : setTimeout;
    schedule(emit, 200);

    // Some Sapphire builds update the WebChannel properties without emitting
    // a change signal for every timeline tick. Poll the cached reactive values
    // so play/pause/position changes still reach the bridge.
    const setIntervalFn = typeof runtime?.setInterval === 'function'
      ? runtime.setInterval.bind(runtime)
      : (typeof setInterval === 'function' ? setInterval : null);
    if (setIntervalFn) pollHandle = setIntervalFn(emit, 250);
  });

  return {
    connected: true,
    dispose() {
      disposed = true;
      const clearIntervalFn = typeof runtime?.clearInterval === 'function'
        ? runtime.clearInterval.bind(runtime)
        : (typeof clearInterval === 'function' ? clearInterval : null);
      if (pollHandle !== null && clearIntervalFn) clearIntervalFn(pollHandle);
      pollHandle = null;
      currentBridge = null;
    }
  };
}

/* --- app.js --- */
const BRIDGE_ORIGIN = 'http://127.0.0.1:18763';
const RECONNECT_DELAYS_MS = [1000, 2000, 4000, 8000, 16000, 30000];
const ids = ['widget-root', 'state-label', 'current-original', 'current-translation', 'next-original', 'settings-toggle', 'settings-panel', 'settings-close', 'font-size-input', 'max-chars-input', 'color-input', 'font-size-output', 'max-chars-output'];
const els = Object.fromEntries(ids.map((id) => [id, document.getElementById(id)]));

let settings = loadSettings();
let editMode = false;
let bridgeSnapshot = null;
const playbackClock = createPlaybackClock();
let reconnectAttempt = 0;
let reconnectTimer = null;
let eventSource = null;
let connectionGeneration = 0;
let visualPreviewMode = null;

function applySettings() {
  const root = els['widget-root'];
  root.style.setProperty('--lyric-size', `${settings.fontSize}px`);
  root.style.setProperty('--lyric-color', settings.color);
  root.style.setProperty('--translation-size', `${Math.round(settings.fontSize * 0.62)}px`);
  root.style.setProperty('--preview-size', `${Math.round(settings.fontSize * 0.56)}px`);
  els['font-size-input'].value = settings.fontSize;
  els['max-chars-input'].value = settings.maxChars;
  els['color-input'].value = settings.color;
  els['font-size-output'].value = `${settings.fontSize}px`;
  els['font-size-output'].textContent = `${settings.fontSize}px`;
  els['max-chars-output'].value = settings.maxChars;
  els['max-chars-output'].textContent = settings.maxChars;
}

function setState(message, tone = 'idle') {
  els['state-label'].textContent = message;
  els['widget-root'].dataset.state = tone;
}

function setText(element, value, hidden = false) {
  element.textContent = value ?? '';
  element.hidden = hidden || !value;
}

function clearLyrics(message = '') {
  setText(els['current-original'], message, !message);
  setText(els['current-translation'], '', true);
  setText(els['next-original'], '', true);
}

function effectivePositionMs() {
  if (!bridgeSnapshot?.playback) return 0;
  return playbackClock.position(bridgeSnapshot.playback);
}

function renderLyrics() {
  if (!bridgeSnapshot?.lyrics?.lines?.length) return;
  const selected = selectDisplayLines(bridgeSnapshot.lyrics.lines, effectivePositionMs(), settings.maxChars);
  setText(els['current-original'], selected.currentOriginal);
  setText(els['current-translation'], selected.currentTranslation);
  setText(els['next-original'], selected.nextOriginal);
}

function renderSnapshot(snapshot) {
  if (!snapshot) {
    bridgeSnapshot = null;
    playbackClock.reset();
    setState('尚未连接歌词服务', 'offline');
    clearLyrics('启动 Lyrics Bridge 后自动识别');
    return;
  }

  const previousSessionId = bridgeSnapshot?.trackSessionId;
  const isNewSession = previousSessionId && previousSessionId !== snapshot.trackSessionId;
  bridgeSnapshot = snapshot;
  playbackClock.update(snapshot.trackSessionId, snapshot.playback);

  if (isNewSession) clearLyrics('正在获取歌词');

  const lyricsStatus = String(snapshot.lyrics?.status ?? '').toLowerCase();
  const bridgeStatus = String(snapshot.bridge?.status ?? '').toLowerCase();
  if (lyricsStatus === 'ready' && snapshot.lyrics.lines?.length) {
    setState('歌词已连接', 'ready');
    renderLyrics();
  } else if (lyricsStatus === 'unavailable') {
    const message = bridgeStatus === 'waitingforplayer' || !snapshot.track
      ? '打开网易云并播放歌曲'
      : '当前歌曲暂无可用歌词';
    setState(message, bridgeStatus === 'waitingforplayer' ? 'idle' : 'warning');
    clearLyrics(message);
  } else if (lyricsStatus === 'error' || bridgeStatus === 'error') {
    setState('歌词暂时不可用', 'error');
    clearLyrics('歌词暂时不可用');
  } else {
    setState('正在获取歌词', 'loading');
    if (!isNewSession) clearLyrics(snapshot.track ? '正在获取歌词' : '打开网易云并播放歌曲');
  }
}

async function fetchSnapshot() {
  const response = await fetch(`${BRIDGE_ORIGIN}/v1/snapshot`, { cache: 'no-store' });
  if (!response.ok) throw new Error(`snapshot HTTP ${response.status}`);
  return response.json();
}

function scheduleReconnect(generation) {
  if (generation !== connectionGeneration) return;
  if (reconnectTimer) clearTimeout(reconnectTimer);
  const delay = RECONNECT_DELAYS_MS[Math.min(reconnectAttempt, RECONNECT_DELAYS_MS.length - 1)];
  reconnectAttempt += 1;
  reconnectTimer = setTimeout(() => {
    reconnectTimer = null;
    connectBridge(generation);
  }, delay);
}

function closeEventSource() {
  if (eventSource) {
    eventSource.close();
    eventSource = null;
  }
}

async function connectBridge(generation = connectionGeneration) {
  if (generation !== connectionGeneration) return;
  closeEventSource();
  try {
    renderSnapshot(await fetchSnapshot());
    if (generation !== connectionGeneration) return;
    const source = new EventSource(`${BRIDGE_ORIGIN}/v1/events`);
    eventSource = source;
    source.addEventListener('snapshot', (event) => {
      try { renderSnapshot(JSON.parse(event.data)); } catch { setState('歌词暂时不可用', 'error'); }
    });
    source.onerror = () => {
      if (eventSource !== source) return;
      closeEventSource();
      setState('尚未连接歌词服务', 'offline');
      scheduleReconnect(generation);
    };
    source.onopen = () => { reconnectAttempt = 0; };
  } catch {
    setState('尚未连接歌词服务', 'offline');
    clearLyrics('启动 Lyrics Bridge 后自动识别');
    scheduleReconnect(generation);
  }
}

function bindSettings() {
  const update = (patch) => { settings = saveSettings({ ...settings, ...patch }); applySettings(); renderLyrics(); };
  els['font-size-input'].addEventListener('input', (event) => update({ fontSize: event.target.value }));
  els['max-chars-input'].addEventListener('input', (event) => update({ maxChars: event.target.value }));
  els['color-input'].addEventListener('input', (event) => update({ color: event.target.value }));
  els['settings-toggle'].addEventListener('click', () => {
    if (editMode) return;
    const open = els['settings-panel'].hidden;
    els['settings-panel'].hidden = !open;
    els['settings-toggle'].setAttribute('aria-expanded', String(open));
  });
  els['settings-close'].addEventListener('click', () => {
    els['settings-panel'].hidden = true;
    els['settings-toggle'].setAttribute('aria-expanded', 'false');
    els['settings-toggle'].focus();
  });
}

function readRuntimeContext() {
  const params = new URLSearchParams(location.search);
  editMode = params.get('edit') === 'true' || params.get('editing') === 'true';
  visualPreviewMode = getVisualPreviewMode(location.search, document.referrer, window.top !== window.self);
  if (editMode) {
    els['settings-panel'].hidden = true;
    els['settings-toggle'].setAttribute('aria-expanded', 'false');
    els['settings-toggle'].disabled = true;
  }
}

function updateResponsiveLayout(width, height) {
  const rect = els['widget-root'].getBoundingClientRect();
  els['widget-root'].dataset.layout = selectResponsiveLayout(width ?? rect.width, height ?? rect.height);
}

function bindRuntimeContext() {
  window.addEventListener('sapphire-context', (event) => {
    const context = event.detail ?? {};
    if (typeof context.theme === 'string') els['widget-root'].dataset.theme = context.theme;
    if (context.editing === true || context.editMode === true) {
      editMode = true;
      els['settings-panel'].hidden = true;
      els['settings-toggle'].setAttribute('aria-expanded', 'false');
      els['settings-toggle'].disabled = true;
    }
  });
  const observer = new ResizeObserver((entries) => {
    const rect = entries[0]?.target?.getBoundingClientRect();
    updateResponsiveLayout(rect?.width, rect?.height);
  });
  observer.observe(els['widget-root']);
  updateResponsiveLayout();
}
async function forwardSapphireUpdate(update) {
  try {
    const response = await fetch(`${BRIDGE_ORIGIN}/v1/smtc`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(update)
    });
    if (!response.ok) console.debug('Sapphire SMTC update rejected', response.status);
  } catch (error) {
    console.debug('Sapphire SMTC bridge fallback active', error);
  }
}

function startSapphireMediaRecognition() {
  // Let Sapphire inject qt.webChannelTransport before constructing QWebChannel.
  // This matches the timing used by Sapphire's official WebChannel example.
  window.setTimeout(() => startSapphireSmtc((update) => forwardSapphireUpdate(update)), 100);
}

function startPositionTicker() {
  const tick = () => {
    if (bridgeSnapshot?.lyrics?.status === 'ready') renderLyrics();
    window.setTimeout(tick, 100);
  };
  tick();
}

readRuntimeContext();
applySettings();
bindSettings();
bindRuntimeContext();
startSapphireMediaRecognition();
setState('正在连接歌词服务');
startPositionTicker();
const visualPreviewSnapshot = createVisualPreviewSnapshot(visualPreviewMode);
if (visualPreviewSnapshot) {
  renderSnapshot(visualPreviewSnapshot);
} else {
  connectionGeneration += 1;
  connectBridge(connectionGeneration);
}
